### Getting Started

In this chapter we will use the NumPy library.  To tell Python that we want to use this library, we run the folowing code.

In [1]:
import numpy as np

This tells Python that we want to use NumPy.  The 'as np' part creates an *alias* so that we don't have to write 'numpy' all the time.  Instead we can just write np.

### N-Dimensional Arrays

The N-Dimensional Array (often abbreviated ndarray) is a multidimensional data structure for holding data.  The most common way to define an ndarray is to use the np.array function.

##### Example 1

In [2]:
#An ndarray
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

The *shape* of this ndarray is $2 \times 3$, since there are 2 rows and 3 columns.  In NumPy, we use the convention that the shape of an array is given by 

number of rows $\times$ number of columns.

Since there are two dimensions (rows and columns), $A$ is a 2-Dimensional Array of shape $2 \times 3$.

We can determine the dimension of an ndarray using the *ndim* attribute.

In [7]:
A.ndim

2

We can determine the shape of an ndarray using the *shape* attribute.

In [6]:
A.shape

(2, 3)

It is relatively clear that $A$ contains all integers.  So, the data type of $A$ should be of integer type.  We can check this using the *dtype* attribute.

In [12]:
A.dtype

dtype('int32')

To illustrate a little bit of the beauty of working with ndarrays, notice how we can treat our array $A$ like a single integer.

In [13]:
2*A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
3+A

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
A**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

$\Box$

A nice way to create an array is using the *reshape* method.

##### Example 2

In [3]:
B = np.array([1,2,3,4,5,6,7,8,9,10])
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
B.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

If -1 is passed as a shape parameter, NumPy will try to figure out what the shape must be.  In the example below, if we are going to have 5 rows, then there must be 2 columns.  So, when NumPy sees 5 rows, it replaces the -1 with 2. 

In [7]:
B.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

$\Box$

##### Example 3

We can access elements in a 2D-array using two indices.  Just like in lists, indexing starts at 0.

In [34]:
#Recall A
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
A[1][2]

6

In [26]:
A[0][1]

2

Using a single index returns a row.

In [27]:
A[0]

array([1, 2, 3])

$\Box$

##### Example 4

In [3]:
x = [1,2,3,4,5,6,7,8]
x[1:5]

[2, 3, 4, 5]

In [2]:
#A new array
C = np.array(list(range(20))).reshape(4,-1)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
C[0:-1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

*Slicing* works much the same as it did with lists, only there can be more dimensions to deal with.  Keep in mind that, just like with .shape, we use the convention that rows come before columns.

In [36]:
C[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [4]:
C[1:4, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [7]:
C[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [6]:
C[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

To grab column 1, we have to tell NumPy first, that we want all rows, then columns 1 to 2-1=1.

In [12]:
C[:, 1:2]

array([[ 1],
       [ 6],
       [11],
       [16]])

To grab rows 1 and 2, we don't have to explicitly pass a second parameter.

In [14]:
C[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

$\Box$

### Other Ways to Define an ndarray

There are other ways to define an ndarry than using the np.array function.  These usually involve defining arrays that have a special form.  

##### Example 5

In [17]:
#Define an array with all entries 1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

$\Box$

##### Example 6

In [35]:
#Define an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

$\Box$

##### Example 7

In [18]:
#Define an array of all zeros
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

$\Box$

This last example is especially useful.  Once an ndarray is defined, its size cannot change.  So, if you plan to populate an array (using a for-loop or other constructs), you need to have an array already initialized.

This drawback to using arrays is reconciled by the speed with which computations can be performed.

##### Exercise 1

Write code so that the following function performs the way that its docstring indicates.  **The first step, initializing a matrix of size (n,n) has been done for you**.

Example: times_table(3) should output a $3 \times 3$ array that looks like $\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}$.

times_table(5) should output a $5 \times 5$ array that looks like $\begin{pmatrix}
    1& 2& 3&4 &5\\
    2& 4& 6& 8& 10 \\
    3& 6& 9& 12& 15 \\
    4&8&12&16&20\\
    5&10&15&20&25
\end{pmatrix}$.

Hint: You will probably need to use nested a for-loop to do this.  Later in this chapter, when we get to vectorization, you will learn a way to do this without nested loops.

In [19]:
def times_table(n):
    """
    Parameters
    -----------
    n: positive integer
    
    Returns
    -----------
    ndarray of shape (n,n) that forms a times table
    """
    A = np.zeros((n,n), dtype = 'int32')

In [ ]:
A = np.array(list(range(1,11))*10).reshape(10,-1)

if not np.allclose(times_table(3), np.array([1,2,3,2,4,6,3,6,9]).reshape(3,3)):
    print("Something is wrong with your code.")
elif not np.allclose(times_table(10), A.T * A):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

### Exotic Indexing Methods

We saw in Examples 3 and 4 how to index a 2D-array using extensions (to handle more dimensions) of the indexing methods we learned for lists.  We will now see other ways to select values from an ndarray.

##### Example 8

In [21]:
X = np.array(range(1,36)).reshape(5,7)
X

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

We can index using an array of boolean values.

In [22]:
boolean_array_rows = np.array([False, True, True, False, False])
boolean_array_rows

array([False,  True,  True, False, False])

In [25]:
X[boolean_array_rows]

array([[ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

If we want to index columns, we need seven boolean values since the array A has shape (5,7).

In [26]:
boolean_array_cols = np.array([True if x%2==0 else False for x in range(7) ])
boolean_array_cols

array([ True, False,  True, False,  True, False,  True])

In [27]:
X[:, boolean_array_cols]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14],
       [15, 17, 19, 21],
       [22, 24, 26, 28],
       [29, 31, 33, 35]])

We can even mix indexing methods.

In [28]:
X[boolean_array_rows, 2:4]

array([[10, 11],
       [17, 18]])

$\Box$

##### Example 9

As an application to the methods in Example 8, suppose that each row of $X$ (from Example 8) corresponds to a letter grade in a class.  Suppose that the grades assigned are A, B, B, C, A and we want to select only the rows corresponding to a letter grade of B.

In [29]:
X

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [30]:
grades = np.array(['A','B','B','C','A'])

In [32]:
X[grades == 'A', :]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [29, 30, 31, 32, 33, 34, 35]])

Now suppose that the columns of X are the grades on HW Assignments 0-6 and we only want to see the scores for Assignments 0,2,4, and 6.

In [34]:
assignments = np.array(range(7))
assignments

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
X[:, assignments%2 == 0]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14],
       [15, 17, 19, 21],
       [22, 24, 26, 28],
       [29, 31, 33, 35]])

$\Box$

##### Example 10

Here, we pass a list of indices to get the rows we want.

In [35]:
#Recall X
X

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [36]:
X[[2,4]]

array([[15, 16, 17, 18, 19, 20, 21],
       [29, 30, 31, 32, 33, 34, 35]])

Now we pass a list of indices to the columns we want.

In [37]:
X[:, [3,4]]

array([[ 4,  5],
       [11, 12],
       [18, 19],
       [25, 26],
       [32, 33]])

When we pass lists of indices for both the rows and the columns, something unexpected happens.

In [38]:
X

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [39]:
X[[1,2], [4,6]]

array([12, 21])

Here, we get an array whose elements are X[1][4] and X[2][6].

$\Box$

### Combining Arrays

We can combine (concatenate) two arrays using the *np.concatenate* function.  

For a 2D-array we could do this by concatenating the rows or by concatenating the columns.  So, we need to tell NumPy whether to concatenate along the rows or the columns.

The way we accomplish this is to pass an *axis* argument to the concatenate function.

For a 2D-array, axis $0$ is the vertical (or row) axis and axis $1$ is the horizontal (or column) axis.

##### Example 11

In [41]:
A = np.array(range(1,7)).reshape(2,-1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
B = np.array(range(10,30)).reshape(2,-1)
B

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [43]:
C = np.array(range(30,45)).reshape(-1,3)
C

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [44]:
np.concatenate([A,B], axis = 1)

array([[ 1,  2,  3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 4,  5,  6, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
np.concatenate([A,B], axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 10

In [65]:
np.concatenate([A,C], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

$\Box$

### Splitting Arrays

We can split an array into two or more sub-arrays using the *np.split* function.

##### Example 12

In [90]:
A = np.array([range(100)]).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
np.split(A, [5], axis = 1)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [92]:
np.split(A, [5], axis = 0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [93]:
x,y,z = np.split(A, [3,7], axis = 1)

In [94]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [60, 61, 62],
       [70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [95]:
y

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76],
       [83, 84, 85, 86],
       [93, 94, 95, 96]])

In [96]:
z

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49],
       [57, 58, 59],
       [67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

$\Box$

##### Exercise 2

Write code so that the following function performs the way that is illustrated in the following examples.  

Example: If $A =\begin{pmatrix}
    1& 2& 3& 4\\
    5& 6& 7& 8 \\
    9& 10& 11& 12 \\
    13& 14& 15& 16\\
\end{pmatrix}$, then swap_regions(A) should return $\begin{pmatrix}
    11& 12& 9& 10\\
    15& 16& 13& 14 \\
    3& 4& 1& 2 \\
    7& 8& 5& 6\\
\end{pmatrix}$.

If $A =\begin{pmatrix}
    1& 2& 3& 4& 5& 6\\
    7& 8& 9& 10& 11& 12 \\
\end{pmatrix}$, then swap_regions(A) should return $\begin{pmatrix}
    10& 11& 12& 7& 8& 9\\
    4& 5& 6& 1& 2& 3 \\
\end{pmatrix}$.

In [15]:
def swap_regions(array):
    """
    Parameters
    -----------
    array: ndarray of shape (m, n) where m and n are even positive integers
    """

In [ ]:
A = np.array(range(1,17)).reshape(4,4)
A1 = np.array([11,12,9,10,15,16,13,14,3,4,1,2,7,8,5,6]).reshape(4,4)
B = np.array(range(1,13)).reshape(2,6)
B1 = np.array([10,11,12,7,8,9,4,5,6,1,2,3]).reshape(2,6)

if not np.allclose(swap_regions(A), A1):
    print("Something is wrong with your code.")
elif not np.allclose(swap_regions(B), B1):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

### Reshaping Arrays

When performing operations on arrays, it is often the case that the shapes don't match up.  NumPy has many methods and functions defined to help change the shape of an ndarray.  

##### Reshape

We have seen the reshape method used a lot so far in this notebook.

##### Example 13    

In [10]:
#An array
A = np.array([1,2,3,4,5,6,7,8,9,10])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
A.shape

(10,)

In [12]:
A.ndim

1

In [13]:
A_reshaped = A.reshape(2,5)
A_reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
A_reshaped.shape

(2, 5)

$\Box$

##### Ravel

The *.ravel* method provides an opposite operation to the *.reshape* operation. 

##### Example 14

In [15]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#From above
A_reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
A_reshaped.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

$\Box$

##### Transpose

Given an array $A$, the transpose $A.T$ is the array whose columns and rows are the rows and columns, respectively, of $A$.

##### Example 14

In [18]:
#An array A
A = np.array(range(20)).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
#The transpose of A
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

$\Box$

### Repeating Elements

##### Repeat



##### Example 15

In [20]:
B = np.array([[0,1,2], [3,4,5]])
B

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
B.repeat([3,3], axis = 0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

If a single integer value is passed, it is interpreted as a list (of the appropriate size) with all entries equal to that integer.

In [23]:
B.repeat(3, axis = 0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [24]:
B

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
B.repeat([3,2,1], axis = 1)

array([[0, 0, 0, 1, 1, 2],
       [3, 3, 3, 4, 4, 5]])

In [26]:
B.repeat(3, axis = 1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [34]:
B.repeat([3,5], axis = 0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

Note that repeat does not modify the original array in-place.

In [36]:
B

array([[0, 1, 2],
       [3, 4, 5]])

$\Box$

##### Tile

##### Example 16

In [37]:
B

array([[0, 1, 2],
       [3, 4, 5]])

Think of the array $B$ as a tile.  A tiling of shape (2,1) has two copies vertically (along axis 0) and one horizontally (along axis 1).

In [39]:
np.tile(B, (2,1))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

A tiling of shape (3,2) has three copies along axis 0 and two copies along axis 1. 

In [40]:
np.tile(B, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

$\Box$

##### Exercise 3

Write code so that the following function performs the way that is illustrated in the following examples.  

Example: If $A =\begin{pmatrix}
    1& 2& 3\\
    5& 6& 7\\
\end{pmatrix}$ and $B =\begin{pmatrix}
    a& b\\
    c& d\\
\end{pmatrix}$, then prod(A, B) should return $\begin{pmatrix}
    1& 2& 3& a& b\\
    1& 2& 3& c& d\\
    5& 6& 7& a& b\\
    5& 6& 7& c& d\\
\end{pmatrix}$.

If $A =\begin{pmatrix}
    1& 2\\
    5& 6\\
\end{pmatrix}$ and $B =\begin{pmatrix}
    a& b\\
    c& d\\
    e& f\\
    g& h\\
\end{pmatrix}$, then prod(A, B) should return $\begin{pmatrix}
    1& 2& a& b\\
    1& 2& c& d\\
    1& 2& e& f\\
    1& 2& g& h\\
    5& 6& a& b\\
    5& 6& c& d\\
    5& 6& e& f\\
    5& 6& g& h\\
\end{pmatrix}$.

In [ ]:
def prod(A,B):
    """
    Parameters
    -----------
    A: ndarray 
    B: ndarray 
    """

In [ ]:
A1 = np.array([1,2]).reshape(1,2)
B1 = np.array([3,4,5]).reshape(3,1)
C1 = np.array([1,2,3,1,2,4,1,2,5]).reshape(3,3)
A2 = np.array(range(9)).reshape(3,3)
B2 = np.array(range(9,11)).reshape(2,1)
C2 = np.array([0,1,2,9,3,4,5,9,6,7,8,9,0,1,2,10,3,4,5,10,6,7,8,10]).reshape(6,4)

if not np.allclose(prod(A1, B1), C1):
    print("Something is wrong with your code.")
elif not np.allclose(prod(A2, B2), C2):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")