In [1]:
import numpy as np
import random

### Universal Functions

Universal Functions are often called *ufuncs*.  ufuncs are functions that perform element-wise operations on ndarrays.  A good first example is the NumPy square root function *np.sqrt*.

##### Example 1

In [4]:
#An array
A = np.array([[4, 9],[16, 25],[36, 49]])
A

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [8]:
np.sqrt(A)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

$\Box$

### Unary Ufuncs

A *unary* universal function is a ufunc that acts on a single ndarray.  The ufunc *np.sqrt* used in Example 1 is an example of a unary ufunc.  A list of unary ufuncs is given in table 4-3 in our course text.

### Binary Ufuncs

*Binary* ufuncs act on two ndarrays.  The most common binary ufunc usage is given in the next example.  

Table 4-4 gives a list of binary ufuncs in our course text.

##### Example 2

In [9]:
#An array
A = np.random.randint(1, 10, size = (4,5))
A

array([[3, 5, 2, 3, 9],
       [3, 1, 5, 9, 6],
       [8, 5, 5, 5, 5],
       [9, 6, 9, 2, 9]])

In [10]:
#Another array
B = np.random.randint(0, 2, size = (4,5))
B

array([[1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0]])

Addition

In [11]:
A+B

array([[ 4,  5,  3,  3,  9],
       [ 4,  2,  6,  9,  7],
       [ 8,  6,  6,  6,  5],
       [ 9,  6, 10,  2,  9]])

Subtraction

In [12]:
A-B

array([[2, 5, 1, 3, 9],
       [2, 0, 4, 9, 5],
       [8, 4, 4, 4, 5],
       [9, 6, 8, 2, 9]])

Element-wise Multiplication.  Don't confuse this with matrix multiplication.

In [13]:
A

array([[3, 5, 2, 3, 9],
       [3, 1, 5, 9, 6],
       [8, 5, 5, 5, 5],
       [9, 6, 9, 2, 9]])

In [14]:
B

array([[1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0]])

In [15]:
A*B

array([[3, 0, 2, 0, 0],
       [3, 1, 5, 0, 6],
       [0, 5, 5, 5, 0],
       [0, 0, 9, 0, 0]])

Element-wise Division  

In [16]:
B/A

array([[0.33333333, 0.        , 0.5       , 0.        , 0.        ],
       [0.33333333, 1.        , 0.2       , 0.        , 0.16666667],
       [0.        , 0.2       , 0.2       , 0.2       , 0.        ],
       [0.        , 0.        , 0.11111111, 0.        , 0.        ]])

Floor Division

In [17]:
B//A

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

$\Box$

##### Exercise 1

Write code so that the following function performs the way that its docstring indicates.

Example: If $A =\begin{pmatrix}
    1& 2\\
    5& 6\\
\end{pmatrix}$ and $B =\begin{pmatrix}
    2& 2\\
    3& 3\\
\end{pmatrix}$, then distance(A, B) should return $\begin{pmatrix}
    1& 0\\
    2& 3\\
\end{pmatrix}$.

Symbolically, if $A =\begin{pmatrix}
    a& b\\
    c& d\\
    e& f\\
    g& h\\
\end{pmatrix}$ and $B =\begin{pmatrix}
    i& j\\
    k& l\\
    m& n\\
    p& q\\
\end{pmatrix}$, then distance(A, B) should return $\begin{pmatrix}
    |a-i|& |b-j|\\
    |c-k|& |d-l|\\
    |e-m|& |f-n|\\
    |g-p|& |h-q|\\
\end{pmatrix}$, where a,b,c,d,e,f,g,h,i,j,k,l,m,n,p,q are numbers.

In [2]:
def distance(A,B):
    """
    Parameters
    -----------
    A: ndarray of type int or float
    B: ndarray of type int or float
    
    Returns
    -----------
    ndarray whose elements have the form |a-b|, where a is an element of A and b is an elment of B
    """
    
    return np.absolute(A-B)

In [11]:
A1 = np.array([1,2,5,6]).reshape(2,2)
B1 = np.array([2,2,3,3]).reshape(2,2)
C1 = np.array([1,0,2,3]).reshape(2,2)
A2 = np.array(range(9)).reshape(3,3)
B2 = np.array(range(9,18)).reshape(3,3)
C2 = np.array([9]*9).reshape(3,3)

if not np.allclose(distance(A1, B1), C1):
    print("Something is wrong with your code.")
elif not np.allclose(distance(A2, B2), C2):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

All tests passed.


##### Example 3

What happens when we add two arrays of different shapes?

In [41]:
A = np.array(range(12)).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
B = np.array([5,5,5]).reshape(1,3)
B

array([[5, 5, 5]])

In [43]:
A+B

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

This is an example of *broadcasting*.  

The shape of $A$ is $4 \times 3$ and the shape of $B$ is $1 \times 3$.  Since the dimensions match in the horizontal (axis = 1) direction, NumPy performs a (3,1) tiling of B to create matrices that can be added.

$\Box$