In [1]:
import numpy as np

### What is Vectorization?

"*Vectorization* is the practice of replacing explicit loops with array expressions."  McKinney 2e, page 110

A simple example will illustrate.

##### Example 1

In [2]:
A = np.random.randint(1, 5, size = (10,))
A

array([2, 1, 2, 4, 1, 1, 3, 4, 4, 1])

Suppose that we want to sum all of the values in A.  

One way to accomplish this task is *explicitly* write a for loop. This approach is NOT vectorization.

In [3]:
sum = 0
for x in A:
    sum+=x
sum

23

The vectorization approach is to use the ndarray *sum* method.

In [4]:
A.sum()

23

$\Box$

"In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents." McKinney 2e, Page 110

##### Example 2

In [5]:
A = np.random.randint(1, 5, size = (90000000,))
A[:10]

array([3, 1, 2, 3, 2, 2, 3, 1, 2, 3])

In [6]:
sum = 0
for x in A:
    sum+=x
sum

224997265

In [7]:
A.sum()

224997265

$\Box$

##### Exercise 1

Given a sequence of *observed values* $y_0,y_1,...,y_N$ and a sequence of *predicted values* $\hat{y_0},\hat{y_1},...,\hat{y_N}$, the *Mean Squared Error* is defined as $$\text{MSE} =\frac{1}{N}((y_1-\hat{y_1})^2+(y_2-\hat{y_2})^2+...+(y_N-\hat{y_N})^2)$$ 

Using summation notation this can be written as $$\text{MSE} = \frac{1}{N}\sum_{i=0}^N(y_i-\hat{y_i})^2$$

In this exercise, your job is to write a function that computes the MSE given an array of observed values and an array of observed values.  You should try to do this using vectorization (no explicit loops).

In [ ]:
def MSE(observed_values, predicted_values):
    """
    Parameters
    -----------
    observed_values: ndarray of shape (N,)
    predicted_values: ndarray of shape (N,)
    
    Returns
    -----------
    float: the MSE of the parameters
    """

In [ ]:
A1 = np.ones((10,))
B1 = np.array([2.0]*10)
A2 = np.array(range(1,11))
B2 = np.array(range(10,0,-1))

if MSE(A1, B1) != 1.0:
    print("Something is wrong with your code.")
elif MSE(A2,B2) != 33.0:
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

$\Box$

### Mathematical Array Methods

NumPy provides many mathematical functions that can be applied to a whole array or along an axis.  Below we show how this is done using the *.sum()* and *.mean()* methods.  Similar usage can be performed for all of the mathematical array methods given in table 4-5 in our course text.

##### Example 3

In [8]:
A = np.array([[1]*3, [2]*3, [3]*3])
A

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

When we don't pass an axis, all values in the entire array are summed.

In [22]:
A.sum()

18

We can sum along an axis.

In [9]:
#Summing the rows
A.sum(axis = 1)

array([3, 6, 9])

In [10]:
#Summing the columns
A.sum(axis = 0)

array([6, 6, 6])

$\Box$

##### Example 4

In [13]:
A = np.random.randint(0,10, size = (5,4))
A

array([[9, 9, 9, 0],
       [1, 6, 7, 6],
       [1, 0, 5, 5],
       [7, 2, 3, 1],
       [2, 1, 8, 7]])

Passing no index gives the mean of all elements in $A$.

In [14]:
A.mean()

4.45

We can compute the mean along an axis.

In [15]:
A.mean(axis = 0)

array([4. , 3.6, 6.4, 3.8])

In [16]:
A.mean(axis = 1)

array([6.75, 5.  , 2.75, 3.25, 4.5 ])

$\Box$

##### Exercise 2

In many Machine Learning applications, it is assumed that the data is *mean-centered*.  A mean-centered data set has the following property:

**The mean (or average) of each column is 0**.

-------------

As a sub-example, consider the following data set: $\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}$.  The mean of the colums are 2, 4, 6, respectively.  The mean-centered version of the data is then $\begin{pmatrix}
    1-2& 2-4& 3-6\\
    2-2& 4-4& 6-6 \\
    3-2& 6-4& 9-6 \\
\end{pmatrix}=\begin{pmatrix}
    -1& -2& -3\\
    0& 0& 0 \\
    1& 2& 3 \\
\end{pmatrix}$.  Notice that the mean (or average) of each column is 0.

-----------------

In this exercise, you are given a data set and it is your job to return the mean-centered version of this data set.  Mean-centering is often called *normalization*.

In [50]:
def normalize(data):
    """
    Parameters
    -----------
    data: ndarray
    
    Returns
    -----------
    ndarray that is the mean-centered version of the data
    """

In [ ]:
D1 = np.array(range(20)).reshape(5,4)
D1_bar = np.array([[-8.0]*4, [-4.0]*4, [0.0]*4, [4.0]*4, [8.0]*4])
D2 = np.array([[1,5,2], [10,30,25], [-1,-3,0]])
D2_bar = np.array([[-2.333, -5.666, -7.0],[6.666, 19.333, 16.0],[-4.333,-13.666, -9.0]])

if not np.allclose(normalize(D1), D1_bar, rtol=1e-7):
    print("Something is wrong with your code.")
elif not np.allclose(normalize(D2), D2_bar, rtol=1e-3):
    print("Something is wrong with your code.")
else:
    print("All tests passed.")

##### Example 5: The Times Table Function

In Exercise 1 on Section 2.0, you created a multiplication times table.  An inefficient way to do this is with nested for-loops.

##### Solution 1

In [17]:
def times_table(n):
    A = np.zeros((n,n), dtype = 'int32')
    for i in range(n):
        for j in range(n):
            A[i][j] = (i+1)*(j+1)
    return A

In [18]:
times_table(3)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

The issue with this method is that it is very slow, especially for large values of n.  A faster way is using vectorization.

The key to seeing how to vectorize these operations is to write

$\begin{pmatrix}
    1& 2& 3\\
    2& 4& 6 \\
    3& 6& 9 \\
\end{pmatrix}=\begin{pmatrix}
    1\cdot 1& 2\cdot 1& 3\cdot 1\\
    1 \cdot 2& 2\cdot 2& 3 \cdot 2 \\
    1 \cdot 3& 2\cdot 3& 3 \cdot 3 \\
\end{pmatrix}=\begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix} * \begin{pmatrix}
    1& 1& 1\\
    2& 2& 2 \\
    3& 3& 3 \\
\end{pmatrix}=\begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix} * \begin{pmatrix}
    1& 2& 3\\
    1& 2& 3 \\
    1& 2& 3 \\
\end{pmatrix}^T$, where $*$ is element-wise (or ufunc) multiplication and the exponent T indicates the transpose operation.

##### Solution 2

In [19]:
def times_table(n):
    A = np.array(list(range(1,n+1))*n).reshape(n,n)
    return A*A.T

In [20]:
times_table(3)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [21]:
times_table(10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Lets compare the speed of these two solutions.

In [22]:
import time
n=5000

In [23]:
#Solution 1
start_time = time.time()
A = np.zeros((n,n), dtype = 'int32')
for i in range(n):
    for j in range(n):
        A[i][j] = (i+1)*(j+1)
print("--- %s seconds ---" % (time.time() - start_time))

--- 11.700715780258179 seconds ---


In [24]:
#Solution 2
start_time = time.time()
A = np.array(list(range(1,n+1))*n).reshape(n,n)
X = A*A.T
print("--- %s seconds ---" % (time.time() - start_time))

--- 2.023688316345215 seconds ---


$\Box$

