In [1]:
import numpy as np

### Broadcasting

*Broadcasting* is a set of rules that describe how NumPy treats arrays with differing dimensions during arithmetic (ufunc) operations.

When a NumPy user attempts to perform arithmetic on two ndarrays of differing shapes, Numpy starts at the rightmost dimension and works left checking if all dimensions are compatible for broadcasting.  If all dimensions are compatible, then broadcasting is used to perform the operation.

Two dimensions are compatible if one or both of the following hold:
+ The dimensions are equal
+ One of them is 1

Note: Missing dimensions are assumed to be 1.

If two arrays are compatible for broadcasting, then the smaller of the broadcasted dimension is increased to match the size of the larger. 

##### Example 1

In [2]:
A =  np.array(range(6)).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
B =  np.array([[10,20,10]])
B

array([[10, 20, 10]])

Are A and B compatible for broadcasting?  Lets look at their shapes.

In [4]:
A.shape

(2, 3)

In [5]:
B.shape

(1, 3)

Working from the right, we see that the rightmost shapes (those along axis 1) match (they are both 3).  Moving left, we see that the shapes along axis 0 do not match, but one of them is 1.  Thus, $B$ will be stretched along axis 0 to have the same shape as $A$.

In [6]:
A+B

array([[10, 21, 12],
       [13, 24, 15]])

$\Box$

Lets see an example where the stretch happens along axis 1.

##### Example 2

In [7]:
C = np.array(range(20)).reshape(5,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
D = np.array([[4*i for i in range(5)]]).T
D

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [9]:
C.shape

(5, 4)

In [10]:
D.shape

(5, 1)

In [11]:
(C*D).shape

(5, 4)

$\Box$

In the next example, an array of shape (1,1) is stretched in both the axis = 0 and axis = 1 directions.

##### Example 3

In [12]:
E = np.array([[1]])
E

array([[1]])

In [13]:
E.shape

(1, 1)

In [14]:
C+E

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
(C+E).shape

(5, 4)

$\Box$

In my opinion, the weirdest stuff happens with 1-Dimensional arrays.  

1-Dimensional arrays have shape (N,), where N is a positive integer.

##### Example 4

In [45]:
A = np.array([1,1,1,1,1])
A

array([1, 1, 1, 1, 1])

In [46]:
A.ndim

1

In [47]:
A.shape

(5,)

One would think that since the shape of $A$ is missing its second component, $A$ will be assumed to have shape (5,1).  If this were the case, then for $B$, as defined below, the operation $A+B$ would stretch $B$ along axis = 1.  

In [16]:
B = np.array([1]*4+[0]*4+[1]*4+[1]*4+[0]*4).reshape(5,4)
B

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0]])

In [17]:
B.shape

(5, 4)

In [18]:
A+B

ValueError: operands could not be broadcast together with shapes (2,3) (5,4) 

Thus, it cannot be the case that $A$, with shape (5,) is assumed to have shape (5,1).  Lets now see what happens when we attempt to perform the operation $A+C$, where $C$ has shape (4,5).

In [57]:
C = np.array([1]*5+[0]*5+[1]*5+[0]*5).reshape(4,5)
C

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

In [58]:
C.shape

(4, 5)

In [59]:
A+C

array([[2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1]])

In [60]:
(A+C).shape

(4, 5)

It must be the case that $A$, with shape (5,), was assumed to have shape (1,5) and the operation $A+B$ stretched $A$ along axis 0. 

$\Box$

For fun, we look at an example performing an operation with 3-Dimensional Arrays. 

##### Example 5

In [19]:
A = np.array([[0,1,2,3,4],[5,6,7,8,9]])
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
B = 2*A
B

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
C = 3*A
C

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [22]:
X = np.array([[10,20,30,40,50]])
X

array([[10, 20, 30, 40, 50]])

In [23]:
Y = 2*X
Y

array([[ 20,  40,  60,  80, 100]])

In [24]:
Z = 3*X
Z

array([[ 30,  60,  90, 120, 150]])

In [25]:
D = np.array([A, B, C])
D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[ 0,  3,  6,  9, 12],
        [15, 18, 21, 24, 27]]])

In [26]:
W = np.array([X, Y, Z])
W

array([[[ 10,  20,  30,  40,  50]],

       [[ 20,  40,  60,  80, 100]],

       [[ 30,  60,  90, 120, 150]]])

In [27]:
D.shape

(3, 2, 5)

In [28]:
W.shape

(3, 1, 5)

In [29]:
D+W

array([[[ 10,  21,  32,  43,  54],
        [ 15,  26,  37,  48,  59]],

       [[ 20,  42,  64,  86, 108],
        [ 30,  52,  74,  96, 118]],

       [[ 30,  63,  96, 129, 162],
        [ 45,  78, 111, 144, 177]]])

In [31]:
D+W == W+D

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [32]:
np.allclose(D+W, W+D)

True

In [30]:
(W+D).shape

(3, 2, 5)

Now lets see what happens when we perform $D+A$.  Remember that $D$ has shape (3,2,5) and $A$ has shape (2,5).

In [81]:
D+A

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[ 0,  3,  6,  9, 12],
        [15, 18, 21, 24, 27]],

       [[ 0,  4,  8, 12, 16],
        [20, 24, 28, 32, 36]]])

In [82]:
(D+A).shape

(3, 2, 5)

We see that $A$ is assumed to have shape (1,2,5) and is stretched along axis 2.

$\Box$